name: 'Build and deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Update website
        run: npm run render

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          single-commit: true
          git-config-name: Tibia boss checker
          git-config-email: bosses@tibiamaps.io
